spring:
  application:
    name: sharp-server-auth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: jkxyx205
server:
  port: 7100

mybatis:
  type-aliases-package: com.yodean.oa.sys.api
  mapper-locations: classpath:mapper/*.xml


dubbo:
  scan: com.yodean.oa.sys.api
  application:
    id: hello
    name: hello
  protocol:
    port: 20880
    id: dubbo
    name: dubbo
    status: server
  registry:
    register: true
    id: zookeeper
    address: zookeeper://127.0.0.1:2181

