spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: jkxyx205

    druid:
      url: jdbc:mysql://127.0.0.1:3306/oa?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: jkxyx205
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.yodean.sys.domain
  mapper-locations: classpath:mapper/*.xml